# Generated by Django 3.1.2 on 2020-10-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('subcategory_1', models.CharField(max_length=50)),
                ('subcategory_2', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('sale', models.BooleanField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
